# Получение гостевого токена
guest_token:
    path: /api/auth/guest-token
    controller: App\Controller\AuthController::getGuestToken
    methods: [POST]
    defaults:
        _format: json

# Обновление токена
refresh_token:
    path: /api/auth/refresh-token
    controller: App\Controller\AuthController::refreshToken
    methods: [POST]
    defaults:
        _format: json

# Запрос кода
request_code:
    path: /api/auth/request-code
    controller: App\Controller\AuthController::requestCode
    methods: [POST]
    defaults:
        _format: json

# Логин
login:
    path: /api/auth/login
    controller: App\Controller\AuthController::login
    methods: [POST]
    defaults:
        _format: json

# Demo endpoints
demo_public:
    path: /api/demo/public
    controller: App\Controller\DemoController::publicInfo
    methods: [GET]
    defaults:
        _format: json

demo_user_only:
    path: /api/demo/user-only
    controller: App\Controller\DemoController::userOnlyInfo
    methods: [GET]
    defaults:
        _format: json

demo_no_role:
    path: /api/demo/no-role
    controller: App\Controller\DemoController::noRoleRequired
    methods: [GET]
    defaults:
        _format: json
