# Конфигурация сервисов
services:
    # Конфигурация по умолчанию для сервисов в папке src/
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Event dispatcher
    event_dispatcher:
        class: Symfony\Component\EventDispatcher\EventDispatcher
        public: true

    # Регистрируем все контроллеры как публичные сервисы
    App\Controller\:
        resource: '../src/Controller/'
        public: true
        tags: ['controller.service_arguments']

    App\Service\:
        resource: '../src/Service/'
    
    # Явная регистрация AuthorizationListener
    App\EventListener\AuthorizationListener:
        public: true
        arguments:
            $jwtService: '@App\Service\JwtService'
    
    # API CORS Listener для обработки всех /api/* эндпоинтов
    App\EventListener\ApiCorsListener:
        public: true